added logos page
kestra-io/docs pull request #1259
Opened 2024-04-25 08:29 UTC by t-chatoyan

2024-05-16 15:40 UTC, tchiotludo requested changes

2024-05-16 15:40 UTC, tchiotludo commented on components/company/Press.vue
> +                  href="https://kestra.io/docs/tutorial/kestra-identity"
```suggestion
                  href="/docs/faq/kestra-identity"
```

2024-05-16 15:40 UTC, tchiotludo commented on components/content/ChildCard.vue
> +    console.log(navigation);
Remove this please

2024-05-16 15:40 UTC, tchiotludo commented on components/content/DownloadLogoPack.vue
> +        href="/Kestra logo kit-20240422T105102Z-001.zip"
```suggestion
        href="/kestra-logo-kit.zip"
```
please use a proper name

2024-07-11 09:39 UTC, anna-geller approved these changes

2024-07-11 09:39 UTC, merged