Adds the article "Data Orchestration Tools Compared: Why Kestra Stands Out for Data Engineers"
kestra-io/docs pull request #1880
Opened 2024-10-17 08:22 UTC by federico-trotta

The main idea is to repropose the same schema of the latest articles but with a focus on data here.

For this reason, the tools present a 'best for' section in this case.

Also, I've strived to not repeat myself, in particular referencing it to [this one](https://github.com/kestra-io/docs/pull/1813). This is why, for example, I mentioned even here the high available scheduler, but in this case I focused on data.

Let me know how we can improve it. :)

2024-10-17 17:03 UTC, wrussell1999 requested changes
I've given this a quick once through and left some comments. I'll give it a more in-depth read once you've addressed the initial feedback!

2024-10-21 13:20 UTC, federico-trotta commented on content/blogs/2024-MM-DD-comparing-data-orchestrators.md
> +- **Cost efficiency**: In data-driven organizations that prioritize budget control, Kestra’s fully open-source nature eliminates the need for paid tiers, making it a more cost-effective solution than
My understanding is that Prefect is not fully open source. It provides a "core" (open-source) and a "cloud version" (paid). In particular, the [cloud version](https://www.restack.io/docs/prefect-knowledge-prefect-open-source-vs-cloud) provides some features more than the core one. For example, if we consider that the cloud version provides "automation" and "email notifications" we can say that Kestra already provides it, and it's fully open-source, thus cost-efficiency.

Another resource is on their [website](https://www.prefect.io/cloud-vs-oss). Here we can see that the cloud version offers webhooks and system metrics...

Let me know if I'm getting this wrong... :)

2024-10-22 14:21 UTC, wrussell1999 commented on content/blogs/2024-MM-DD-comparing-data-orchestrators.md
> +- **Cost efficiency**: In data-driven organizations that prioritize budget control, Kestra’s fully open-source nature eliminates the need for paid tiers, making it a more cost-effective solution than
Ah gotcha. I still think that we're in a similar situation as them where we have an enterprise edition that has a bunch of non open source features too. Instead you could word it that we allow you to host on prem for both offerings, and not limited to the cloud @federico-trotta

2024-10-22 15:49 UTC, federico-trotta commented on content/blogs/2024-MM-DD-comparing-data-orchestrators.md
> +- **Cost efficiency**: In data-driven organizations that prioritize budget control, Kestra’s fully open-source nature eliminates the need for paid tiers, making it a more cost-effective solution than
how about that @wrussell1999 ? :)

2024-10-23 11:17 UTC, wrussell1999 commented on content/blogs/2024-MM-DD-comparing-data-orchestrators.md
> +Data [orchestration](./2024-09-18-what-is-an-orchestrator.md) is an automated process that combines and organizes data from different data sources. You can think of it like being the conductor of a m
```suggestion
Data [orchestration](./2024-09-18-what-is-an-orchestrator.md) is orchestration of workflow nodes that touch data. You can think of it like being the conductor of a massive data symphony that involves the automated coordination and management of data as it moves between different systems and processes. Imagine having to manually manage every data pipeline, handle dependencies, schedule tasks, and monitor workflows: that would be a nightmare, right? Well, data orchestration tools take care of all that heavy lifting for you.

```

2024-10-23 11:18 UTC, anna-geller commented on content/blogs/2024-MM-DD-comparing-data-orchestrators.md
> +- **Cost efficiency**: In data-driven organizations that prioritize budget control, Kestra’s fully open-source nature eliminates the need for paid tiers, making it a more cost-effective solution than
Federico, when comparing OSS tools, you should check the LICENSE in each repo. Prefect is fully open source with Apache 2.0 license, same as kestra and dagster

2024-10-23 11:36 UTC, federico-trotta commented on content/blogs/2024-MM-DD-comparing-data-orchestrators.md
> +- **Cost efficiency**: In data-driven organizations that prioritize budget control, Kestra’s fully open-source nature eliminates the need for paid tiers, making it a more cost-effective solution than
thank you! I recently came across the concept of "source-available" which, possibly, led me to some confusion.

2024-10-28 16:27 UTC, closed without merging