added blueprint and blueprint details page inside page directory
kestra-io/docs pull request #496
Opened 2023-09-12 08:13 UTC by mageexcel

2023-09-13 04:45 UTC, mageexcel commented
@Skraye , Can you please tell me what this is for?
![image](https://github.com/kestra-io/docs/assets/49708265/e329fa8b-58b6-4db5-9262-0779c3e7bb99)

2023-09-13 05:02 UTC, tchiotludo commented
> @Skraye , Can you please tell me what this is for? ![image](https://user-images.githubusercontent.com/49708265/267538082-e329fa8b-58b6-4db5-9262-0779c3e7bb99.png)

It's the pagination size, you can skip for now

2023-09-13 12:54 UTC, mageexcel commented
Should I add this static for now
![image](https://github.com/kestra-io/docs/assets/49708265/ec095a28-a3f6-481f-a097-07209a124a1f)

2023-09-13 13:38 UTC, tchiotludo commented
> Should I add this static for now ![image](https://user-images.githubusercontent.com/49708265/267659721-ec095a28-a3f6-481f-a097-07209a124a1f.png)

It should be dynamic and feed from the api

2023-09-13 13:45 UTC, mageexcel commented
> It should be dynamic and feed from the api

But, I don't have the api right now so, can you please tell me how I should make it dynamic as I don't know in which format data will come from the api.

2023-09-13 13:47 UTC, Skraye commented
I'll send you an API example in chat and some details!

2023-09-13 13:47 UTC, mageexcel commented
> I'll send you an API example in chat and some details!

Okay @Skraye thanks

2023-09-14 07:07 UTC, Skraye requested changes
Be careful about responsiveness :
![image](https://github.com/kestra-io/docs/assets/37600690/9e96028a-e550-4d28-ade5-94ca6d88fdb3)

2023-09-14 07:07 UTC, Skraye commented on components/blueprints/About.vue
> +    <div class="description">{{ description }}</div>
This has to be displayed has markdown

2024-01-02 18:42 UTC, tchiotludo commented
close in favor of https://github.com/kestra-io/docs/pull/557

2024-01-02 18:42 UTC, closed without merging