create terraform-provider ui
kestra-io/docs pull request #556
Opened 2023-10-03 17:58 UTC by mageexcel

2023-10-05 16:50 UTC, anna-geller commented on components/terraform/Header.vue
> +                    <p>Manage and deploy Kestra workflows directly within your existing Terraform environment, eliminating the need for separate configurations.</p>
```suggestion
                    <h1>Kestra Terraform Provider: Deploy All Your Workflows <br/> in a CI/CD Process</h1>
                    <p>Manage and deploy Kestra workflows directly within your existing Terraform environment, eliminating the need for separate configurations.</p>
```
there must be a line break before "in a CI/CD Process"

2023-10-05 16:52 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <p>Leveraging the Kestra Terraform Provider allows you to manage your Kestra resources along with other infrastructural components, all from a single platform.</p>
```suggestion
                        <p>The Terraform Provider allows you to manage your Kestra resources in code, along with other infrastructure components, all from a single platform.</p>
```

2023-10-05 16:53 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <p>By using Terraform, you benefit from all the Infrastructure as Code (IaC) best practices, making it easier to version control, collaborate, and maintain your Kestra configu
```suggestion
                        <p>By using Terraform, you benefit from the Infrastructure as Code (IaC) best practices, making it easier to version control, collaborate, and maintain your Kestra configurations.</p>
```

2023-10-05 17:00 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <p>The provider is built on Kestra's API-first architecture, ensuring seamless integration and greater flexibility in managing your data workflows.</p>
```suggestion
                        <p>The provider is built on top of Kestra's API, allowing you to programmatically manage all resources, from workflows, namespaces, and secrets, to user management.</p>
```

2023-10-05 17:01 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <h3>Declarative Configurations</h3>
```suggestion
                        <h3>Declarative Configuration</h3>
```

2023-10-05 17:07 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <p>Terraform uses its HashiCorp Configuration Language (HCL), while Kestra flows are defined in YAML. This alignment in philosophy ensures not only a smooth transition but als
```suggestion
                        <p>Terraform uses its HashiCorp Configuration Language (HCL), while Kestra flows are defined in YAML. This alignment in declarative interfaces ensures not only a smooth transition but also makes it easy to use both technologies together.</p>
```

2023-10-05 17:07 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <h3>Comprehensive & Modular Resource Management</h3>
```suggestion
                        <h3>Modular Resource Management</h3>
```

2023-10-05 17:09 UTC, anna-geller commented on components/terraform/Overview.vue
> +                        <p>Our Terraform provider for Kestra is designed to easily manage your Kestra resources using Terraform. This includes, among others, flows, namespace, and user management, as
```suggestion
                        <p>Kestra's Terraform provider is designed to easily manage your resources using Terraform. This includes, among others, flows, namespace, and user management, as well as secrets. Check the list of available resources in our <NuxtLink href="/docs/terraform">documentation.</NuxtLink></p>
```

2023-10-05 17:10 UTC, anna-geller commented on components/terraform/Overview.vue
> +                <p class="mt-5 text-white">Additionally, the inherent modularity in both Terraform and Kestra's configurations allows you to create reusable blocks of code. These can be shared across
```suggestion
                <p class="mt-5 text-white">The inherent modularity in both, Terraform and Kestra, allows you to create reusable blocks of code. These can be shared across multiple teams or projects, contributing to maintainable operations.</p>
```

2023-10-05 17:11 UTC, anna-geller commented on components/terraform/UseCases.vue
> +    <LayoutSection title="Use Cases">
```suggestion
    <LayoutSection title="Benefits of the Integration">
```

2023-10-05 17:12 UTC, anna-geller commented on components/terraform/Footer.vue
> +                        <p>Integration between Kestra and Terraform is straightforward. Add the Kestra provider to your Terraform main configuration file to get started.</p>
```suggestion
                        <p>Integration between Kestra and Terraform is simple. Add the Kestra provider to your Terraform configuration file to get started.</p>
```

2023-10-12 10:10 UTC, Skraye commented
UI changes
Benefits of integration, images have strange background instead of just dot :
![image](https://github.com/kestra-io/docs/assets/37600690/9344a167-56cc-44b2-9d4a-65db4f69168d)
Overview, Missing halo effect around image (first website, second figma): 
![image](https://github.com/kestra-io/docs/assets/37600690/df9af365-b77a-4410-b278-a8ba2d142655)
![image](https://github.com/kestra-io/docs/assets/37600690/fdb3124c-6885-408c-bbad-4a8ba09527aa)

2023-10-12 10:14 UTC, Skraye requested changes

2023-10-12 10:14 UTC, Skraye commented on components/terraform/Footer.vue
> +        background: #2A1940;
Add a variable, create one if necessary, so we can list all colors used in website

2023-10-12 10:14 UTC, Skraye commented on components/terraform/Header.vue
> +        background-image: linear-gradient(#2A1940, #2A1940), radial-gradient(circle at top left, #B010FB 18.11%, #DE97FF 27.65%, #A227DB 36.31%, rgba(162, 39, 219, 0) 58.84%, rgba(166, 16, 236, 0.84)
using existing class instead :  btn-animated btn-purple-animated

2023-10-12 10:14 UTC, Skraye commented on components/terraform/Overview.vue
> +            color: #CFCEFF;
Add a variable, create one if necessary, so we can list all colors used in website

2023-10-12 10:14 UTC, Skraye commented on components/terraform/Overview.vue
> +    background-color: #110221;
Add a variable, create one if necessary, so we can list all colors used in website

2023-10-12 10:14 UTC, Skraye commented on components/terraform/Overview.vue
> +        color: #CFCEFF;
Add a variable, create one if necessary, so we can list all colors used in website

2023-10-12 10:14 UTC, Skraye commented on pages/terraform-provider.vue
> +    background-color: #0F011D;
Add a variable, create one if necessary, so we can list all colors used in website

2023-10-23 07:01 UTC, merged