added api call for get plugins
kestra-io/docs pull request #711
Opened 2023-12-26 10:12 UTC by t-chatoyan

2023-12-26 16:56 UTC, Skraye requested changes
Strange number in the breadcrumb : 
![image](https://github.com/kestra-io/docs/assets/37600690/fca079e4-6189-40a4-a8d8-400f6b58bbab)

Same exact call is being done multiple times (1 for each different type of task I think) when picking a plugin : 
![image](https://github.com/kestra-io/docs/assets/37600690/5107713a-ba36-4918-8edb-c1cba85252f2)

2023-12-26 16:56 UTC, Skraye commented on components/plugins/Breadcrumb.vue
> +            breadcrumbLinkExist(item, index) {
Missing some logic I think

2023-12-26 16:56 UTC, Skraye commented on components/plugins/Container.vue
> +            .replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '');
Please add a description, not very readable for next people working on it

2024-01-10 08:27 UTC, ridge-kimani commented on components/content/ProseA.vue
> +                if (link.match(/(\.\.\/){2,}/) && page.value._file.includes('index.md')) {
Let's add some comments to the conditions that resolve the regexes.

2024-01-10 15:16 UTC, brian-mulier-p commented
Closing in favor of #762

2024-01-10 15:16 UTC, closed without merging